name: mocha_hive
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: Bitter
      fonts:
        - asset: assets/fonts/Bitter/Bitter-Regular.ttf
        - asset: assets/fonts/Bitter/Bitter-Bold.ttf
        - asset: assets/fonts/Bitter/Bitter-ExtraBold.ttf
        - asset: assets/fonts/Bitter/Bitter-Thin.ttf
        - asset: assets/fonts/Bitter/Bitter-Medium.ttf
        - asset: assets/fonts/Bitter/Bitter-ExtraLight.ttf
